# Assignment 1
### By: Sutharsan Kesavan

***

#### Question 1

B. RAINBOW

#### Question 2

In [3]:
print("LETS UPGRADE")

LETS UPGRADE


In [126]:
s = "lets upgrade"
print(s.upper())

LETS UPGRADE


#### Question 3

In [10]:
cost = int(input())
sell = int(input())

if sell>cost:
    print("Profit")
elif sell < cost:
    print("Loss")
else:
    print("Neither")

 19
 95


Profit


#### Question 4

In [12]:
euro = int(input())
print(euro*80)

 18


1440


#### Question 5

In [15]:
l = []
for i in range(10):
    temp = int(input())
    if temp%2 == 0:
        l.append(temp)
        
print(l)

 1
 2
 3
 4
 5
 6
 7
 8
 9
 10


[2, 4, 6, 8, 10]


#### Question 6

LIST COMPREHENSION

In [18]:
# get a new list which contains "a" in the previous list
vehicles = ["car", "van", "bus", "lorry", "truck"]
newlist = []

newlist = [x for x in vehicles if "a" in x]

print(newlist)

['car', 'van']


In [19]:
# get a new list without an element in the previous list
newlist1 = [x for x in vehicles if x != "car"]
print(newlist1)

['van', 'bus', 'lorry', 'truck']


In [20]:
# get all the elements in a new list
newlist2 = [x for x in vehicles]
print(newlist2)

['car', 'van', 'bus', 'lorry', 'truck']


In [21]:
# use the range() function to create an iterable:
newlist3 = [x for x in range(5)]
print(newlist3)

[0, 1, 2, 3, 4]


In [22]:
# accept only even numbers
newlist4 = [x for x in range(10) if x%2 == 0]
print(newlist4)

[0, 2, 4, 6, 8]


In [23]:
# Set the values in the new list to upper case
newlist5 = [x.upper() for x in vehicles]
print(newlist5)

['CAR', 'VAN', 'BUS', 'LORRY', 'TRUCK']


In [24]:
# Set all values in the new list to 'hello'
newlist6 = ["Hello" for x in vehicles]
print(newlist6)

['Hello', 'Hello', 'Hello', 'Hello', 'Hello']


In [25]:
# Return "aeroplane" instead of "lorry"
newlist7 = [x if x != "lorry" else "aeroplane" for x in vehicles]
print(newlist7)

['car', 'van', 'bus', 'aeroplane', 'truck']


#### Question 7

In [28]:
n = int(input())

dicts = {}
for i in range(1,n+1):
    dicts[i] = i*i
        
print(dicts)

 8


{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


#### Question 8

In [57]:
import numpy as np

In [59]:
ls = []
no = int(input())
for i in range(no):
    tmp = input()
    ls.append(tmp)
    
for i in ls:
    m , n = map(str,i.split())
    if m == "UP":
        u = int(n)
    elif m == "DOWN":
        d = int(n)
    elif m == "RIGHT":
        r = int(n)
    else:
        l = int(n)
    
dist = round(np.sqrt((u-d)**2 + (l-r)**2))
print(dist)

 4
 UP 5
 DOWN 3
 LEFT 3
 RIGHT 2


2


#### Question 9

In [61]:
arr = np.arange(2,50,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

#### Question 10

In [94]:
a = []
b = []
print("Enter first set of 5 nubers: ")
for i in range(5):
    n = int(input())
    a.append(n)
    
print("Enter second set of 5 nubers: ")
for i in range(5):
    m = int(input())
    b.append(m)

arr1 = np.array(a)
arr2 = np.array(b)

arr3 = np.concatenate([arr1,arr2])
print("Concatenated array:", arr3)
arr3.sort()
print("Sorted Array: ",arr3)

Enter first set of 5 nubers: 


 5
 1
 2
 9
 3


Enter second set of 5 nubers: 


 15
 12
 19
 16
 21


Concatenated array: [ 5  1  2  9  3 15 12 19 16 21]
Sorted Array:  [ 1  2  3  5  9 12 15 16 19 21]


#### Question 11

In [95]:
def dimAndsize (arr):
    print("Dimension of the array: ", arr.ndim)
    print("Size of the array: ", arr.size)

In [97]:
a = np.arange(5)
dimAndsize(a)

Dimension of the array:  1
Size of the array:  5


In [98]:
b = np.arange(12).reshape((3, 4))
dimAndsize(b)

Dimension of the array:  2
Size of the array:  12


In [99]:
c = np.arange(24).reshape((2, 3, 4))
dimAndsize(c)

Dimension of the array:  3
Size of the array:  24


#### Question 12

In [102]:
# 1D array 
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])

# To convert to 2D array 
# we can use the np.newaxis to increase the dimesions in a array
# Using np.newaxis will increase the dimensions of your array by one dimension when used once. 
# inserting a axis at the first index creates a row vector

two_dim_arr = one_dim_arr[np.newaxis, :]

print(one_dim_arr, "Dimension :",one_dim_arr.ndim)
print(two_dim_arr, "Dimension :",two_dim_arr.ndim)

[1 2 3 4 5 6] Dimension : 1
[[1 2 3 4 5 6]] Dimension : 2


In [103]:
# for column vector, insert axis at the second index
two_dim_arr = one_dim_arr[:,np.newaxis]

print(one_dim_arr, "Dimension :",one_dim_arr.ndim)
print(two_dim_arr, "Dimension :",two_dim_arr.ndim)

[1 2 3 4 5 6] Dimension : 1
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] Dimension : 2


In [104]:
# we can also expand an array by inserting a new axis at a specified position with np.expand_dims.
two_dim_arr = np.expand_dims(one_dim_arr,axis = 0)

print(one_dim_arr, "Dimension :",one_dim_arr.ndim)
print(two_dim_arr, "Dimension :",two_dim_arr.ndim)

[1 2 3 4 5 6] Dimension : 1
[[1 2 3 4 5 6]] Dimension : 2


In [105]:
two_dim_arr = np.expand_dims(one_dim_arr,axis = 1)

print(one_dim_arr, "Dimension :",one_dim_arr.ndim)
print(two_dim_arr, "Dimension :",two_dim_arr.ndim)

[1 2 3 4 5 6] Dimension : 1
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] Dimension : 2


#### Question 13

In [117]:
m = np.arange(1,5).reshape((2,2))
n = np.arange(10,14).reshape((2,2))
print("Array 1: ")
print(m)
print()
print("Array 2: ")
print(n)

Array 1: 
[[1 2]
 [3 4]]

Array 2: 
[[10 11]
 [12 13]]


In [118]:
# vstack
np.vstack((m,n))

array([[ 1,  2],
       [ 3,  4],
       [10, 11],
       [12, 13]])

In [119]:
# hstack
np.hstack((m,n))

array([[ 1,  2, 10, 11],
       [ 3,  4, 12, 13]])

#### Question 14

In [122]:
# Get unique values in a numpy array
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18])
print('Original Numpy Array : ' , arr)

# Get unique values from a numpy array
uniqueValues = np.unique(arr)
print('Unique Values : ',uniqueValues)

Original Numpy Array :  [11 11 12 13 14 15 16 17 12 13 11 14 18]
Unique Values :  [11 12 13 14 15 16 17 18]


In [124]:
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18])
print('Original Numpy Array : ' , arr)

# Get a tuple of unique values & their frequency in numpy array
uniqueValues, occurCount = np.unique(arr, return_counts=True)
print("Unique Values : " , uniqueValues)
print("Occurrence Count : ", occurCount)

Original Numpy Array :  [11 11 12 13 14 15 16 17 12 13 11 14 18]
Unique Values :  [11 12 13 14 15 16 17 18]
Occurrence Count :  [3 2 2 2 1 1 1 1]


In [125]:
# Get unique values in a numpy array
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18])
print('Original Numpy Array : ' , arr)

# Get unique values from a numpy array
uniqueValues = np.unique(arr)
print('Unique Values : ',uniqueValues)
print('No of Unique elements : ',len(uniqueValues))

Original Numpy Array :  [11 11 12 13 14 15 16 17 12 13 11 14 18]
Unique Values :  [11 12 13 14 15 16 17 18]
No of Unique elements :  8
